# Generated by Django 4.1.2 on 2022-10-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_transcription_delete_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='url',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='transcription',
            unique_together={('url', 'language')},
        ),
    ]
